name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18.3
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: test
        run: |
          go test -v ./...
